package synthesizer

import (
	"context"

	"github.com/heythisissud/ip-sakti-backend/internal/retriever"
	"github.com/heythisissud/ip-sakti-backend/pkg/domain"
)

// Synthesize generates an IPRoadmap from a classification and retrieved evidence.
// STUB: returns a hardcoded roadmap for the demo Ashwagandha/Shallaki scenario.
// Real synthesis via Anthropic Claude is wired in a later deliverable.
func Synthesize(_ context.Context, _ *domain.ClassificationResult, _ []retriever.RetrievalResult) (*domain.IPRoadmap, error) {
	return &domain.IPRoadmap{
		ProductSummary: "Proprietary Ayurvedic joint-pain formulation combining Ashwagandha " +
			"(Withania somnifera) and Shallaki (Boswellia serrata) sourced from India, " +
			"intended for sale in India and Germany.",
		Classification: "Proprietary Ayurvedic formulation with Indian bio-resources and " +
			"traditional knowledge involvement.",
		Domains: []domain.DomainAnalysis{
			{
				Domain:  domain.DomainPatent,
				Status:  domain.StatusRelevant,
				Finding: "Your formulation combines Ashwagandha and Shallaki in a novel ratio for joint-pain relief. While individual ingredient use is in the public domain, a specific synergistic formulation with defined extract ratios may qualify for patent protection in India under the Patents Act 1970. PCT filing will be required for Germany market entry.",
				KeyRisks: []string{
					"Prior art risk: TKDL (Traditional Knowledge Digital Library) may have overlapping formulations.",
					"Novelty of combination must be demonstrable over classical Ayurvedic texts.",
					"German patent office requires clinical evidence for health claims.",
				},
				Citations:       []domain.Citation{},
				Confidence:      0.78,
				NeedsEscalation: false,
			},
			{
				Domain:  domain.DomainABS,
				Status:  domain.StatusRelevant,
				Finding: "Both Ashwagandha and Shallaki are Indian biological resources. Accessing and commercialising these resources triggers obligations under India's Biological Diversity Act 2002 and the Nagoya Protocol (for Germany, an EU signatory). ABS compliance requires filing with the National Biodiversity Authority (NBA) before commercial exploitation.",
				KeyRisks: []string{
					"Non-compliance with Biological Diversity Act is a criminal offence.",
					"EU regulations require a due-diligence declaration under the Nagoya Protocol for German sales.",
					"Failure to obtain NBA approval before commercialisation can result in product ban.",
				},
				Citations:       []domain.Citation{},
				Confidence:      0.91,
				NeedsEscalation: true,
			},
			{
				Domain:  domain.DomainRegulatory,
				Status:  domain.StatusRelevant,
				Finding: "In India, a proprietary Ayurvedic formulation requires a manufacturing licence under Schedule T of the Drugs & Cosmetics Act and must be labelled per AYUSH guidelines. For Germany, the formulation will be regulated as a Traditional Herbal Medicinal Product (THMP) under EU Directive 2004/24/EC, requiring a simplified registration with 30 years of traditional use evidence (15 years in the EU).",
				KeyRisks: []string{
					"Proprietary name must not imply a cure for a scheduled disease without clinical trials.",
					"EU THMP registration is lengthy (18–24 months); early regulatory strategy is advised.",
					"Labelling in Germany must comply with BfArM requirements in German language.",
				},
				Citations:       []domain.Citation{},
				Confidence:      0.85,
				NeedsEscalation: false,
			},
		},
		NextSteps: []string{
			"File an NBA Access and Benefit Sharing (ABS) disclosure with the National Biodiversity Authority before any commercial activity, to avoid penalties under the Biological Diversity Act 2002.",
			"Commission a TKDL freedom-to-operate search and a patent novelty search (India + PCT) to assess patentability of your specific formulation ratios before investment in clinical trials.",
			"Engage an AYUSH-registered consultant to prepare the Drug Master File and apply for a manufacturing licence under Schedule T of the Drugs & Cosmetics Act.",
		},
		HumanEscalation: []domain.EscalationItem{
			{
				Reason:   "Biodiversity Act compliance and NBA ABS filing involve regulatory penalties if mishandled. An expert review is strongly recommended before commercial launch.",
				ProfType: "Biodiversity/ABS Legal Specialist",
				Urgency:  "high",
			},
			{
				Reason:   "German THMP registration under EU Directive 2004/24/EC is a complex multi-year process requiring a qualified person (QP) and regulatory affairs specialist familiar with BfArM procedures.",
				ProfType: "EU Regulatory Affairs Consultant",
				Urgency:  "medium",
			},
		},
		OverallConfidence: 0.74,
		Disclaimer:        "This analysis is generated by an AI system and is provided for informational purposes only. It does not constitute legal advice, regulatory guidance, or a professional opinion. Always consult a qualified IP attorney, regulatory consultant, or legal professional before making commercial decisions.",
	}, nil
}
